require 'rails_helper'

RSpec.describe Relationship, type: :model do
  before do 
    @relationship = FactoryBot.create(:relationship)
  end

  it "can be generated by FactoryBot" do
    puts @relationship.follower
    puts @relationship.followed
  end 

  it "is valid with associated follower user and followed user" do
    expect(@relationship).to be_valid
  end

  it "is invalid without an associated follower user" do
    @relationship.follower = nil
    expect(@relationship).to_not be_valid
  end

  it "is invalid without an associated followed user" do
    @relationship.followed = nil
    expect(@relationship).to_not be_valid
  end
end
